name: prostatemr
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - cpython=3.12.12
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=21.1.7
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pyzmq=27.1.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - pip:
      - absl-py==2.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - graphviz==0.21
      - grpcio==1.76.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - monai==1.5.1
      - mpmath==1.3.0
      - networkx==3.6.1
      - nibabel==5.3.3
      - numpy==2.3.5
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==6.33.2
      - pyparsing==3.2.5
      - pytz==2025.2
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - torchinfo==1.8.0
      - torchvision==0.24.1
      - torchviz==0.0.3
      - tzdata==2025.2
      - werkzeug==3.1.4
prefix: /opt/anaconda3/envs/prostatemr
